name: Uses SonarScanner for dotnet
description: A GitHub Action to install sonarscanner with java, in a platform agnostic way
author: NOS Inovação
branding:
  color: blue
  icon: search

inputs:
  version:
    description: The version of the scanner to be used
    required: false
    default: 6.2.0
  step:
    description: The step to be used
    required: true
    default: 'begin'
  sonar-url:
    description: The url of the sonar server
    required: true
  sonar-token:
    description: The token of the sonar server
    required: true
  project-key:
    description: The project key of the sonar server
    required: true
  extra-args:
    description: Extra arguments to be used
    required: false
  shell:
    description: The shell to be used
    required: false
    default: powershell


runs:
  using: composite
  steps:
  - name: install sonar-scanner via dotnet tool
    shell: ${{ inputs.shell }}
    run: dotnet tool install --global dotnet-sonarscanner --version ${{ inputs.version }}
  - name: run sonar-scanner
    shell: ${{ inputs.shell }}
    run: |
      if ($env:step -eq "end") {
        dotnet sonarscanner $env:step /d:sonar.login="${{ inputs.sonar-token }}" ${{ inputs.extra-args }}
      }
      else {
        dotnet sonarscanner $env:step /k:"${{ inputs.project-key }}" /d:sonar.login="${{ inputs.sonar-token }}" /d:sonar.host.url="${{ inputs.sonar-url }}" ${{ inputs.extra-args }}
      }