name: Uses SonarScanner for dotnet
description: A GitHub Action to install sonarscanner with java, in a platform agnostic way
author: NOS Inovação
branding:
  color: blue
  icon: search

inputs:
  version:
    description: The version of the scanner to be used
    required: false
    default: 6.2.0
  step:
    description: The step to be used
    required: true
    default: 'begin'
  sonar-url:
    description: The url of the sonar server
    required: true
  sonar-token:
    description: The token of the sonar server
    required: true
  project-key:
    description: The project key of the sonar server
    required: true
  extra-args:
    description: Extra arguments to be used
    required: false
  shell:
    description: The shell to be used
    required: false
    default: powershell


runs:
  using: composite
  steps:
  - name: export env vars for the input
    if: ${{ inputs.shell == 'powershell' }}
    shell: ${{ inputs.shell }}
    run: echo "step=${{ inputs.step }}" >> $env:GITHUB_ENV
  - name: export env vars for the input
    if: ${{ inputs.shell == 'bash' }}
    shell: ${{ inputs.shell }}
    run: export step=${{ inputs.step }}
  - name: install sonar-scanner via dotnet tool
    shell: ${{ inputs.shell }}
    run: dotnet tool install --global dotnet-sonarscanner --version ${{ inputs.version }}
  - name: run sonar-scanner windows
    if: ${{ inputs.shell == 'powershell' }}
    shell: ${{ inputs.shell }}
    run: |
      if ($env:step -eq "end") {
        dotnet sonarscanner $env:step /d:sonar.token="${{ inputs.sonar-token }}" ${{ inputs.extra-args }}
      }
      else {
        dotnet sonarscanner $env:step /k:"${{ inputs.project-key }}" /d:sonar.token="${{ inputs.sonar-token }}" /d:sonar.host.url="${{ inputs.sonar-url }}" ${{ inputs.extra-args }}
      }
  - name: run sonar-scanner linux
    if: ${{ inputs.shell == 'bash' }}
    shell: ${{ inputs.shell }}
    run: |
      if [ "$step" = "end" ]; then
        dotnet sonarscanner $step /d:sonar.token="${inputs.sonar-token}" "${inputs.extra-args}"
      else
        dotnet sonarscanner $step /k:"${inputs.project-key}" /d:sonar.token="${inputs.sonar-token}" /d:sonar.host.url="${inputs.sonar-url}" "${inputs.extra-args}"
      fi
